<?php
/**
 * EduTrack — Admin: Bulk CSV Course Enrollment
 *
 * Method:  POST  (multipart/form-data)
 * URL:     /api/admin/enrollment_bulk.php
 * Access:  Admin only
 *
 * Accepts a CSV generated by an external school system with one student per row.
 * The academic_year is always read from system settings — it is NOT in the CSV.
 *
 * Expected CSV columns (header row optional, detected by presence of "reg" in col-0):
 *   reg_number, full_name, course_code, year_of_study, semester
 *
 * Processing rules:
 *   - Unknown reg_number  → skip row, add to "errors" list
 *   - Duplicate in CSV    → skip silently (de-dup by reg+course+year+sem)
 *   - Already enrolled    → skip (idempotent), counted as "skipped"
 *   - No units for combo  → enroll in course succeeds with zero units (warning)
 *                           student will be auto-enrolled when units are added later
 *
 * Success response (200):
 *   {
 *     "success": true,
 *     "enrolled": int,       -- new course enrollments created
 *     "skipped": int,        -- already enrolled (course-level)
 *     "errors": [ { "row": int, "reg_number": str, "reason": str } ],
 *     "warnings": [ { "reg_number": str, "course_code": str, "reason": str } ],
 *     "message": string
 *   }
 */

defined('EDUTRACK_LOADED') or define('EDUTRACK_LOADED', true);
require_once __DIR__ . '/../../config/config.php';
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../backend/middleware/auth.php';
require_once __DIR__ . '/../../backend/models/UserModel.php';

Auth::startSession();
header('Content-Type: application/json; charset=utf-8');
Auth::requireRole('admin', true);
Auth::verifyCsrf(true);

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method not allowed.']);
    exit;
}

// ── Validate file upload ──────────────────────────────────────────────────────
if (empty($_FILES['csv_file']) || $_FILES['csv_file']['error'] !== UPLOAD_ERR_OK) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'CSV file upload failed or missing.']);
    exit;
}

$csvTmpPath = $_FILES['csv_file']['tmp_name'];
if (!is_uploaded_file($csvTmpPath)) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'Invalid file upload.']);
    exit;
}

// ── Academic year from system settings ────────────────────────────────────────
$academicYear = DB::row(
    "SELECT setting_value FROM system_settings WHERE setting_key = 'academic_year'"
)['setting_value'] ?? '';

if (empty($academicYear)) {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'message' => 'Active academic year is not configured in System Settings. Please set it before enrolling students.',
    ]);
    exit;
}

// ── Parse CSV ─────────────────────────────────────────────────────────────────
$handle = fopen($csvTmpPath, 'r');
if ($handle === false) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Unable to read uploaded CSV.']);
    exit;
}

$enrolled = 0;
$skipped  = 0;
$errors   = [];
$warnings = [];
$seen     = [];   // de-dup key: "reg|course_code|year|sem"
$rowNum   = 0;
$adminId  = Auth::id();

while (($cols = fgetcsv($handle)) !== false) {
    $rowNum++;

    // Skip blank lines
    if (count($cols) === 0 || (count($cols) === 1 && trim($cols[0]) === '')) {
        continue;
    }

    // Auto-detect and skip header row (first row where col-0 looks like a label)
    $col0 = strtolower(trim($cols[0] ?? ''));
    if ($rowNum === 1 && (
        $col0 === 'reg_number' || $col0 === 'reg' || $col0 === 'registration' ||
        $col0 === 'student_id' || $col0 === 'id'
    )) {
        continue;
    }

    // Extract columns (be lenient — allow 3-column CSVs without full_name)
    $regNumber  = strtoupper(trim($cols[0] ?? ''));
    // col 1 is full_name (informational only — we don't use it; reg_number is canonical)
    $courseCode = strtoupper(trim($cols[2] ?? $cols[1] ?? ''));
    $yearOfStudy = (int) trim($cols[3] ?? $cols[2] ?? '0');
    $semester    = (int) trim($cols[4] ?? $cols[3] ?? '0');

    // Basic validation
    if ($regNumber === '') {
        continue; // truly blank row
    }

    if ($courseCode === '' || $yearOfStudy <= 0 || !in_array($semester, [1, 2], true)) {
        $errors[] = [
            'row'        => $rowNum,
            'reg_number' => $regNumber,
            'reason'     => 'Missing or invalid course_code, year_of_study, or semester.',
        ];
        continue;
    }

    // De-duplicate within the same CSV
    $dupKey = "{$regNumber}|{$courseCode}|{$yearOfStudy}|{$semester}";
    if (isset($seen[$dupKey])) {
        continue;
    }
    $seen[$dupKey] = true;

    // Look up student
    $student = UserModel::findByRegNumber($regNumber);
    if (!$student || $student['role'] !== 'student') {
        $errors[] = [
            'row'        => $rowNum,
            'reg_number' => $regNumber,
            'reason'     => 'Student not found in EduTrack. Create the account first, then re-upload.',
        ];
        continue;
    }

    // Look up course by code
    $course = DB::row("SELECT id, code, name FROM courses WHERE code = ?", [$courseCode]);
    if (!$course) {
        $errors[] = [
            'row'        => $rowNum,
            'reg_number' => $regNumber,
            'reason'     => "Course code '{$courseCode}' not found.",
        ];
        continue;
    }

    // Enroll (idempotent — already_existed flag tells us if it was a duplicate)
    $result = UserModel::enrollStudentInCourse(
        $student['id'],
        $course['id'],
        $yearOfStudy,
        $academicYear,
        $semester,
        'csv',
        $adminId
    );

    if (!$result['success']) {
        $errors[] = [
            'row'        => $rowNum,
            'reg_number' => $regNumber,
            'reason'     => $result['message'],
        ];
        continue;
    }

    if ($result['already_existed']) {
        $skipped++;
    } else {
        $enrolled++;
    }

    // Warn if zero units for this combo (enrollment still succeeds)
    if ($result['zero_units'] && !$result['already_existed']) {
        $warnings[] = [
            'reg_number'  => $regNumber,
            'course_code' => $courseCode,
            'reason'      => "No active units for {$courseCode} Year {$yearOfStudy} Semester {$semester}. "
                           . "Student enrolled and will be auto-assigned to units when they are added.",
        ];
    }
}
fclose($handle);

Auth::audit('bulk_enrollment_csv', 'student_course_enrollments', null, [
    'academic_year' => $academicYear,
    'enrolled'      => $enrolled,
    'skipped'       => $skipped,
    'errors'        => count($errors),
    'warnings'      => count($warnings),
]);

$parts = [];
if ($enrolled > 0) $parts[] = "{$enrolled} enrolled";
if ($skipped  > 0) $parts[] = "{$skipped} already enrolled (skipped)";
if (count($errors) > 0)   $parts[] = count($errors) . " error(s)";
if (count($warnings) > 0) $parts[] = count($warnings) . " warning(s)";

echo json_encode([
    'success'  => true,
    'academic_year' => $academicYear,
    'enrolled' => $enrolled,
    'skipped'  => $skipped,
    'errors'   => $errors,
    'warnings' => $warnings,
    'message'  => implode(', ', $parts) ?: 'No rows processed.',
]);
